[32mINFO    [0m custom_logger1:test_login.py:34 ************ test_login_positive STARTED ************
[31m[1mERROR   [0m custom_logger1:test_login.py:56 ************ test_login_positive FAILED ************